<script lang="ts">
  import { page } from '$app/state';
  import { onMount } from 'svelte';

  let sidebarCollapsed = false;
  let showBotToken = false;
  $: editing = page.url.searchParams.has('edit');

  onMount(() => {
    sidebarCollapsed = localStorage.getItem('znayu.sidebar.collapsed') === 'true';
  });

  function toggleSidebar() {
    sidebarCollapsed = !sidebarCollapsed;
    localStorage.setItem('znayu.sidebar.collapsed', String(sidebarCollapsed));
  }
</script>

<svelte:head><title>{editing ? 'Edit notification' : 'Create notification'} — Znayu</title><meta name="description" content="Manage a notification channel in the Znayu admin console." /></svelte:head>

<main class:sidebar-collapsed={sidebarCollapsed} class="notification-create-page">
  <aside class="sidebar" aria-label="Operator navigation"><div class="sidebar-top"><a class="wordmark" href="/dashboard">znayu</a><span class="console-label">Console</span><button class="sidebar-toggle" type="button" aria-label={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'} onclick={toggleSidebar}><svg aria-hidden="true" viewBox="0 0 20 20"><rect x="3.5" y="3.5" width="13" height="13" rx="2" /><path d="M8 3.5v13" />{#if sidebarCollapsed}<path d="m10.5 7 3 3-3 3" />{:else}<path d="m12.5 7-3 3 3 3" />{/if}</svg></button></div><div class="create-actions"><a class="sidebar-create" href="/monitors/new"><span aria-hidden="true">+</span> Create monitor</a><a class="sidebar-create secondary" href="/status-pages/new">Create status page</a></div><nav class="sidebar-nav"><a href="/dashboard"><svg aria-hidden="true" viewBox="0 0 20 20"><path d="M3 10h5V3H3v7Zm9 7h5v-7h-5v7ZM3 17h5v-4H3v4Zm9-14v4h5V3h-5Z" /></svg>Overview</a><a href="/status-pages"><svg aria-hidden="true" viewBox="0 0 20 20"><path d="M3 4.5h14v11H3v-11Zm3 3h8M6 11h5" /></svg>Status pages</a><a class="active" href="/monitors"><svg aria-hidden="true" viewBox="0 0 20 20"><path d="M3 15.5V4.5h14v11H3Zm3-3 2-2 2 1.5 3-4 2 2.5" /></svg>Monitors</a><a href="/activity"><svg aria-hidden="true" viewBox="0 0 20 20"><path d="M10 3v7l4 2M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z" /></svg>Activity</a></nav><div class="sidebar-bottom"><div class="operator"><span class="operator-avatar">JS</span><span><strong>Jordan Smith</strong><small>Owner</small></span><button type="button">More</button></div></div></aside>
  <header class="notification-header"><a class="back-link" href="/monitors">← Back to monitors</a><p class="section-kicker">Admin console</p><h1>{editing ? 'Edit notification' : 'Create notification'} <span class="info-dot" title="Create a reusable notification channel.">i</span></h1></header>
  <section class="notification-shell"><form onsubmit={(event) => event.preventDefault()}><div class="notification-card"><div><h2>Configure notification</h2><p>Create a channel that can be reused by multiple monitors.</p></div><div class="fields"><label for="type">Notification type<select id="type"><option>Telegram</option><option>Discord</option><option>Email</option><option>Webhook</option></select></label><label for="alias">Alias<input id="alias" type="text" placeholder="My Telegram Alert" /></label><label for="token">Bot token<div class="secret"><input id="token" type={showBotToken ? 'text' : 'password'} /><button type="button" onclick={() => showBotToken = !showBotToken}>{showBotToken ? 'Hide' : 'Show'}</button></div></label><small>You can get the bot token from <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">BotFather</a>.</small><label for="chat">Chat ID<input id="chat" type="text" /></label><small>Supports a direct chat, group, or channel ID.</small><label for="thread">(Optional) Thread ID<input id="thread" type="text" /></label><label for="server">(Optional) Server URL<input id="server" type="url" value="https://api.telegram.org" /></label></div><div class="toggles"><label><input type="checkbox" /> Send silently</label><small>Users will not receive a sound notification.</small><label><input type="checkbox" /> Protect against forwarding and saving</label><small>Protect messages sent by the Telegram bot.</small><hr /><label><input type="checkbox" checked /> Enabled by default</label></div></div><footer><p>Notification configuration is only previewed in this prototype.</p><div><button class="test" type="button">Test</button><button class="save" type="submit">Save notification</button></div></footer></form></section>
</main>

<style>
  .notification-create-page { min-height: 100svh; display: grid; grid-template-columns: 232px minmax(0, 1fr); background: var(--page); color: var(--ink); }.sidebar { position: fixed; inset: 0 auto 0 0; z-index: 2; display: flex; width: 232px; min-height: 100svh; padding: 22px 14px 16px; flex-direction: column; background: #141821; border-right: 1px solid var(--border); }.sidebar-top { display: flex; align-items: baseline; justify-content: space-between; padding: 0 10px; }.wordmark { color: var(--ink); font-size: 1.65rem; font-weight: 720; letter-spacing: -0.045em; text-decoration: none; }.console-label, .section-kicker { color: var(--muted); font-size: 0.6875rem; letter-spacing: 0.02em; text-transform: uppercase; }.sidebar-toggle { display: grid; width: 24px; height: 24px; place-items: center; padding: 0; border: 1px solid var(--border-light); border-radius: 5px; color: var(--muted); background: transparent; cursor: pointer; }.sidebar-toggle svg { width: 14px; height: 14px; fill: none; stroke: currentColor; stroke-linecap: round; stroke-width: 1.5; }.create-actions { display: grid; gap: 8px; margin: 38px 0 28px; }.sidebar-create { display: flex; min-height: 38px; align-items: center; justify-content: center; border: 1px solid var(--green); border-radius: 5px; color: var(--page); background: var(--green); font-size: 0.8125rem; font-weight: 650; text-decoration: none; }.sidebar-create.secondary { border-color: var(--border-light); color: var(--secondary); background: transparent; }.sidebar-nav { display: grid; gap: 3px; }.sidebar-nav a { padding: 10px; border-radius: 5px; color: var(--secondary); font-size: 0.8125rem; text-decoration: none; }.sidebar-nav a:hover, .sidebar-nav a.active { color: var(--ink); background: var(--surface-hover); }
  .notification-create-page.sidebar-collapsed { grid-template-columns: 72px minmax(0, 1fr); }.sidebar-collapsed .sidebar { width: 72px; padding-right: 10px; padding-left: 10px; }.sidebar-collapsed .wordmark, .sidebar-collapsed .console-label, .sidebar-collapsed .sidebar-create.secondary { display: none; }.sidebar-collapsed .sidebar-top { justify-content: center; }.sidebar-collapsed .create-actions { justify-items: center; }.sidebar-collapsed .sidebar-create { width: 40px; font-size: 0; }.sidebar-collapsed .sidebar-nav a { padding-right: 8px; padding-left: 8px; overflow: hidden; font-size: 0; }
  .notification-header, .notification-shell { grid-column: 2; width: min(100%, 992px); margin-right: auto; margin-left: auto; }.notification-header { padding-top: 60px; }.back-link { display: inline-flex; min-height: 34px; align-items: center; margin-bottom: 28px; padding: 0 11px; border: 1px solid var(--border-light); border-radius: 5px; color: var(--secondary); background: var(--surface); font-size: 0.8125rem; text-decoration: none; }.notification-header .section-kicker { margin: 0 0 7px; }.notification-header h1 { margin: 0; font-size: 1.65rem; letter-spacing: -0.03em; }.info-dot { display: inline-grid; width: 15px; height: 15px; place-items: center; border-radius: 50%; color: var(--page); background: var(--muted); font-size: 0.6875rem; vertical-align: 3px; }
  .notification-shell { margin-top: 32px; overflow: hidden; border: 1px solid var(--border); border-radius: 12px; background: var(--surface); }.notification-card { display: grid; gap: 26px; padding: 30px; }.notification-card h2 { margin: 0; font-size: 1rem; }.notification-card p { margin: 7px 0 0; color: var(--secondary); font-size: 0.8125rem; }.fields { display: grid; gap: 15px; }.fields label { display: grid; gap: 7px; color: var(--secondary); font-size: 0.8125rem; font-weight: 600; }.fields input, .fields select { width: 100%; height: 42px; padding: 0 12px; border: 1px solid var(--border-light); border-radius: 5px; color: var(--ink); background: var(--page); font: inherit; font-size: 0.8125rem; }.fields select { appearance: none; }.fields small, .toggles small { color: var(--muted); font-size: 0.6875rem; }.fields a { color: var(--secondary); }.secret { display: flex; }.secret input { border-radius: 5px 0 0 5px; }.secret button { width: 72px; border: 1px solid var(--border-light); border-left: 0; border-radius: 0 5px 5px 0; color: var(--secondary); background: var(--surface-hover); }.toggles { display: grid; gap: 8px; }.toggles label { color: var(--secondary); font-size: 0.8125rem; }.toggles input { accent-color: var(--green); }.toggles hr { width: 100%; margin: 10px 0; border: 0; border-top: 1px solid var(--border); }
  footer { display: flex; align-items: center; justify-content: space-between; gap: 20px; padding: 14px 18px; border-top: 1px solid var(--border); background: rgb(15 18 26 / 50%); }footer p { color: var(--muted); font-size: 0.6875rem; }footer div { display: flex; gap: 10px; }footer button { min-width: 120px; min-height: 38px; border-radius: 5px; font: inherit; font-size: 0.8125rem; font-weight: 650; cursor: pointer; }.test { border: 1px solid var(--amber); color: var(--page); background: var(--amber); }.save { border: 1px solid var(--green); color: var(--page); background: var(--green); }
  @media (max-width: 760px) { .notification-create-page { display: block; padding: 18px 14px 36px; }.sidebar { position: static; width: auto; min-height: auto; margin: -18px -14px 0; padding: 14px 12px; }.sidebar-toggle { display: none; }.notification-header, .notification-shell { width: 100%; }.notification-header { padding-top: 0; }.notification-shell { margin-top: 32px; }.notification-card { padding: 24px 20px 28px; }footer { align-items: flex-start; flex-direction: column; }footer div, footer button { width: 100%; }footer div { display: grid; grid-template-columns: 1fr 1fr; } }
  .sidebar-nav a { display: flex; align-items: center; gap: 11px; }.sidebar-nav svg { display: block; width: 16px; height: 16px; flex: 0 0 auto; fill: none; stroke: currentColor; stroke-linecap: round; stroke-linejoin: round; stroke-width: 1.5; }.sidebar-nav a:first-child svg { fill: currentColor; stroke: none; }.sidebar-bottom { display: grid; gap: 20px; margin-top: auto; }.operator { display: flex; align-items: center; gap: 9px; padding: 12px 8px 0; border-top: 1px solid var(--border); }.operator-avatar { display: grid; width: 28px; height: 28px; place-items: center; border-radius: 50%; color: var(--page); background: var(--green); font-size: .6875rem; font-weight: 700; }.operator > span:nth-child(2) { display: grid; gap: 2px; min-width: 0; }.operator strong, .operator small { display: block; }.operator strong { color: var(--secondary); font-size: .6875rem; }.operator small { color: var(--muted); font-size: .6875rem; }.operator button { margin-left: auto; border: 0; color: var(--muted); background: transparent; font-size: .6875rem; }.notification-shell { margin-bottom: 64px; }
</style>
